version: "3"

volumes:
  postgresql:
  redis:

networks:
  simple-admin:
    driver: bridge

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: "simple_admin"
      POSTGRESQL_PASSWORD: "simple-admin."
    volumes:
      - postgresql:/bitnami/postgresql
    networks:
      simple-admin:
        aliases:
          - postgresql-server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M
        reservations:
          cpus: "0.05"
          memory: 200M

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      simple-admin:
        aliases:
          - redis-server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.05"
          memory: 200M

  core-rpc:
    image: registry.cn-hangzhou.aliyuncs.com/simple_admin/core-rpc-docker:v1.7.2
    container_name: core-rpc
    restart: always
    ports:
      - '9101:9101'
    networks:
      simple-admin:
        aliases:
          - core-rpc
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.05"
          memory: 200M

  core-api:
    image: registry.cn-hangzhou.aliyuncs.com/simple_admin/core-api-docker:v1.7.2
    container_name: core-api
    restart: always
    #    environment:
    #      I18N_DIR: ''
    #      AUTH_SECRET: 'jS6VKDtsJf3z1n2VKDtsJf3z1n2'
    ports:
      - "9100:9100"
    networks:
      simple-admin:
        aliases:
          - core-api
    volumes:
      - ./api/etc:/app/etc
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.05"
          memory: 200M