FROM golang:1.19.1-alpine3.16 as builder

WORKDIR /home
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && cd rpc \
    && go build -o /home/rpc/core_rpc core.go

FROM alpine:latest

LABEL MAINTAINER="RyanSU@yuansu.china.work@gmail.com"

WORKDIR /home

COPY --from=builder /home/rpc/core_rpc ./
COPY --from=builder /home/rpc/etc/core.yaml ./

EXPOSE 9101
ENTRYPOINT ./core_rpc -f core.yaml