FROM golang:1.20.3-alpine3.17 as builder

# Define the project name | 定义项目名称
ARG PROJECT=core

WORKDIR /build
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && cd api \
    && go build -ldflags="-s -w" -o /build/api/${PROJECT}_api ${PROJECT}.go

FROM alpine:latest

# Define the project name | 定义项目名称
ARG PROJECT=core
# Define the config file name | 定义配置文件名
ARG CONFIG_FILE=core.yaml
# Define the author | 定义作者
ARG AUTHOR=yuansu.china.work@gmail.com

LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app
ENV PROJECT=${PROJECT}
ENV CONFIG_FILE=${CONFIG_FILE}

COPY --from=builder /build/api/${PROJECT}_api ./
COPY --from=builder /build/api/etc/${CONFIG_FILE} ./etc/

EXPOSE 9100
ENTRYPOINT ./${PROJECT}_api -f etc/${CONFIG_FILE}