// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-core/rpc/ent/menu"
	"github.com/suyuan32/simple-admin-core/rpc/ent/role"
)

// MenuCreate is the builder for creating a Menu entity.
type MenuCreate struct {
	config
	mutation *MenuMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MenuCreate) SetCreatedAt(v time.Time) *MenuCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MenuCreate) SetNillableCreatedAt(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MenuCreate) SetUpdatedAt(v time.Time) *MenuCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MenuCreate) SetNillableUpdatedAt(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *MenuCreate) SetSort(v uint32) *MenuCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *MenuCreate) SetNillableSort(v *uint32) *MenuCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *MenuCreate) SetParentID(v uint64) *MenuCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *MenuCreate) SetNillableParentID(v *uint64) *MenuCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetMenuLevel sets the "menu_level" field.
func (_c *MenuCreate) SetMenuLevel(v uint32) *MenuCreate {
	_c.mutation.SetMenuLevel(v)
	return _c
}

// SetMenuType sets the "menu_type" field.
func (_c *MenuCreate) SetMenuType(v uint32) *MenuCreate {
	_c.mutation.SetMenuType(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *MenuCreate) SetPath(v string) *MenuCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *MenuCreate) SetNillablePath(v *string) *MenuCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MenuCreate) SetName(v string) *MenuCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRedirect sets the "redirect" field.
func (_c *MenuCreate) SetRedirect(v string) *MenuCreate {
	_c.mutation.SetRedirect(v)
	return _c
}

// SetNillableRedirect sets the "redirect" field if the given value is not nil.
func (_c *MenuCreate) SetNillableRedirect(v *string) *MenuCreate {
	if v != nil {
		_c.SetRedirect(*v)
	}
	return _c
}

// SetComponent sets the "component" field.
func (_c *MenuCreate) SetComponent(v string) *MenuCreate {
	_c.mutation.SetComponent(v)
	return _c
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_c *MenuCreate) SetNillableComponent(v *string) *MenuCreate {
	if v != nil {
		_c.SetComponent(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *MenuCreate) SetDisabled(v bool) *MenuCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *MenuCreate) SetNillableDisabled(v *bool) *MenuCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetServiceName sets the "service_name" field.
func (_c *MenuCreate) SetServiceName(v string) *MenuCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_c *MenuCreate) SetNillableServiceName(v *string) *MenuCreate {
	if v != nil {
		_c.SetServiceName(*v)
	}
	return _c
}

// SetPermission sets the "permission" field.
func (_c *MenuCreate) SetPermission(v string) *MenuCreate {
	_c.mutation.SetPermission(v)
	return _c
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_c *MenuCreate) SetNillablePermission(v *string) *MenuCreate {
	if v != nil {
		_c.SetPermission(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *MenuCreate) SetTitle(v string) *MenuCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *MenuCreate) SetIcon(v string) *MenuCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetHideMenu sets the "hide_menu" field.
func (_c *MenuCreate) SetHideMenu(v bool) *MenuCreate {
	_c.mutation.SetHideMenu(v)
	return _c
}

// SetNillableHideMenu sets the "hide_menu" field if the given value is not nil.
func (_c *MenuCreate) SetNillableHideMenu(v *bool) *MenuCreate {
	if v != nil {
		_c.SetHideMenu(*v)
	}
	return _c
}

// SetHideBreadcrumb sets the "hide_breadcrumb" field.
func (_c *MenuCreate) SetHideBreadcrumb(v bool) *MenuCreate {
	_c.mutation.SetHideBreadcrumb(v)
	return _c
}

// SetNillableHideBreadcrumb sets the "hide_breadcrumb" field if the given value is not nil.
func (_c *MenuCreate) SetNillableHideBreadcrumb(v *bool) *MenuCreate {
	if v != nil {
		_c.SetHideBreadcrumb(*v)
	}
	return _c
}

// SetIgnoreKeepAlive sets the "ignore_keep_alive" field.
func (_c *MenuCreate) SetIgnoreKeepAlive(v bool) *MenuCreate {
	_c.mutation.SetIgnoreKeepAlive(v)
	return _c
}

// SetNillableIgnoreKeepAlive sets the "ignore_keep_alive" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIgnoreKeepAlive(v *bool) *MenuCreate {
	if v != nil {
		_c.SetIgnoreKeepAlive(*v)
	}
	return _c
}

// SetHideTab sets the "hide_tab" field.
func (_c *MenuCreate) SetHideTab(v bool) *MenuCreate {
	_c.mutation.SetHideTab(v)
	return _c
}

// SetNillableHideTab sets the "hide_tab" field if the given value is not nil.
func (_c *MenuCreate) SetNillableHideTab(v *bool) *MenuCreate {
	if v != nil {
		_c.SetHideTab(*v)
	}
	return _c
}

// SetFrameSrc sets the "frame_src" field.
func (_c *MenuCreate) SetFrameSrc(v string) *MenuCreate {
	_c.mutation.SetFrameSrc(v)
	return _c
}

// SetNillableFrameSrc sets the "frame_src" field if the given value is not nil.
func (_c *MenuCreate) SetNillableFrameSrc(v *string) *MenuCreate {
	if v != nil {
		_c.SetFrameSrc(*v)
	}
	return _c
}

// SetCarryParam sets the "carry_param" field.
func (_c *MenuCreate) SetCarryParam(v bool) *MenuCreate {
	_c.mutation.SetCarryParam(v)
	return _c
}

// SetNillableCarryParam sets the "carry_param" field if the given value is not nil.
func (_c *MenuCreate) SetNillableCarryParam(v *bool) *MenuCreate {
	if v != nil {
		_c.SetCarryParam(*v)
	}
	return _c
}

// SetHideChildrenInMenu sets the "hide_children_in_menu" field.
func (_c *MenuCreate) SetHideChildrenInMenu(v bool) *MenuCreate {
	_c.mutation.SetHideChildrenInMenu(v)
	return _c
}

// SetNillableHideChildrenInMenu sets the "hide_children_in_menu" field if the given value is not nil.
func (_c *MenuCreate) SetNillableHideChildrenInMenu(v *bool) *MenuCreate {
	if v != nil {
		_c.SetHideChildrenInMenu(*v)
	}
	return _c
}

// SetAffix sets the "affix" field.
func (_c *MenuCreate) SetAffix(v bool) *MenuCreate {
	_c.mutation.SetAffix(v)
	return _c
}

// SetNillableAffix sets the "affix" field if the given value is not nil.
func (_c *MenuCreate) SetNillableAffix(v *bool) *MenuCreate {
	if v != nil {
		_c.SetAffix(*v)
	}
	return _c
}

// SetDynamicLevel sets the "dynamic_level" field.
func (_c *MenuCreate) SetDynamicLevel(v uint32) *MenuCreate {
	_c.mutation.SetDynamicLevel(v)
	return _c
}

// SetNillableDynamicLevel sets the "dynamic_level" field if the given value is not nil.
func (_c *MenuCreate) SetNillableDynamicLevel(v *uint32) *MenuCreate {
	if v != nil {
		_c.SetDynamicLevel(*v)
	}
	return _c
}

// SetRealPath sets the "real_path" field.
func (_c *MenuCreate) SetRealPath(v string) *MenuCreate {
	_c.mutation.SetRealPath(v)
	return _c
}

// SetNillableRealPath sets the "real_path" field if the given value is not nil.
func (_c *MenuCreate) SetNillableRealPath(v *string) *MenuCreate {
	if v != nil {
		_c.SetRealPath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MenuCreate) SetID(v uint64) *MenuCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_c *MenuCreate) AddRoleIDs(ids ...uint64) *MenuCreate {
	_c.mutation.AddRoleIDs(ids...)
	return _c
}

// AddRoles adds the "roles" edges to the Role entity.
func (_c *MenuCreate) AddRoles(v ...*Role) *MenuCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoleIDs(ids...)
}

// SetParent sets the "parent" edge to the Menu entity.
func (_c *MenuCreate) SetParent(v *Menu) *MenuCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Menu entity by IDs.
func (_c *MenuCreate) AddChildIDs(ids ...uint64) *MenuCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Menu entity.
func (_c *MenuCreate) AddChildren(v ...*Menu) *MenuCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the MenuMutation object of the builder.
func (_c *MenuCreate) Mutation() *MenuMutation {
	return _c.mutation
}

// Save creates the Menu in the database.
func (_c *MenuCreate) Save(ctx context.Context) (*Menu, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MenuCreate) SaveX(ctx context.Context) *Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MenuCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := menu.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := menu.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := menu.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := menu.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := menu.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.Redirect(); !ok {
		v := menu.DefaultRedirect
		_c.mutation.SetRedirect(v)
	}
	if _, ok := _c.mutation.Component(); !ok {
		v := menu.DefaultComponent
		_c.mutation.SetComponent(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := menu.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.ServiceName(); !ok {
		v := menu.DefaultServiceName
		_c.mutation.SetServiceName(v)
	}
	if _, ok := _c.mutation.HideMenu(); !ok {
		v := menu.DefaultHideMenu
		_c.mutation.SetHideMenu(v)
	}
	if _, ok := _c.mutation.HideBreadcrumb(); !ok {
		v := menu.DefaultHideBreadcrumb
		_c.mutation.SetHideBreadcrumb(v)
	}
	if _, ok := _c.mutation.IgnoreKeepAlive(); !ok {
		v := menu.DefaultIgnoreKeepAlive
		_c.mutation.SetIgnoreKeepAlive(v)
	}
	if _, ok := _c.mutation.HideTab(); !ok {
		v := menu.DefaultHideTab
		_c.mutation.SetHideTab(v)
	}
	if _, ok := _c.mutation.FrameSrc(); !ok {
		v := menu.DefaultFrameSrc
		_c.mutation.SetFrameSrc(v)
	}
	if _, ok := _c.mutation.CarryParam(); !ok {
		v := menu.DefaultCarryParam
		_c.mutation.SetCarryParam(v)
	}
	if _, ok := _c.mutation.HideChildrenInMenu(); !ok {
		v := menu.DefaultHideChildrenInMenu
		_c.mutation.SetHideChildrenInMenu(v)
	}
	if _, ok := _c.mutation.Affix(); !ok {
		v := menu.DefaultAffix
		_c.mutation.SetAffix(v)
	}
	if _, ok := _c.mutation.DynamicLevel(); !ok {
		v := menu.DefaultDynamicLevel
		_c.mutation.SetDynamicLevel(v)
	}
	if _, ok := _c.mutation.RealPath(); !ok {
		v := menu.DefaultRealPath
		_c.mutation.SetRealPath(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MenuCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Menu.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Menu.updated_at"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "Menu.sort"`)}
	}
	if _, ok := _c.mutation.MenuLevel(); !ok {
		return &ValidationError{Name: "menu_level", err: errors.New(`ent: missing required field "Menu.menu_level"`)}
	}
	if _, ok := _c.mutation.MenuType(); !ok {
		return &ValidationError{Name: "menu_type", err: errors.New(`ent: missing required field "Menu.menu_type"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Menu.name"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Menu.title"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Menu.icon"`)}
	}
	return nil
}

func (_c *MenuCreate) sqlSave(ctx context.Context) (*Menu, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MenuCreate) createSpec() (*Menu, *sqlgraph.CreateSpec) {
	var (
		_node = &Menu{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(menu.Table, sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(menu.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(menu.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(menu.FieldSort, field.TypeUint32, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.MenuLevel(); ok {
		_spec.SetField(menu.FieldMenuLevel, field.TypeUint32, value)
		_node.MenuLevel = value
	}
	if value, ok := _c.mutation.MenuType(); ok {
		_spec.SetField(menu.FieldMenuType, field.TypeUint32, value)
		_node.MenuType = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(menu.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(menu.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Redirect(); ok {
		_spec.SetField(menu.FieldRedirect, field.TypeString, value)
		_node.Redirect = value
	}
	if value, ok := _c.mutation.Component(); ok {
		_spec.SetField(menu.FieldComponent, field.TypeString, value)
		_node.Component = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(menu.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(menu.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := _c.mutation.Permission(); ok {
		_spec.SetField(menu.FieldPermission, field.TypeString, value)
		_node.Permission = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(menu.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(menu.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.HideMenu(); ok {
		_spec.SetField(menu.FieldHideMenu, field.TypeBool, value)
		_node.HideMenu = value
	}
	if value, ok := _c.mutation.HideBreadcrumb(); ok {
		_spec.SetField(menu.FieldHideBreadcrumb, field.TypeBool, value)
		_node.HideBreadcrumb = value
	}
	if value, ok := _c.mutation.IgnoreKeepAlive(); ok {
		_spec.SetField(menu.FieldIgnoreKeepAlive, field.TypeBool, value)
		_node.IgnoreKeepAlive = value
	}
	if value, ok := _c.mutation.HideTab(); ok {
		_spec.SetField(menu.FieldHideTab, field.TypeBool, value)
		_node.HideTab = value
	}
	if value, ok := _c.mutation.FrameSrc(); ok {
		_spec.SetField(menu.FieldFrameSrc, field.TypeString, value)
		_node.FrameSrc = value
	}
	if value, ok := _c.mutation.CarryParam(); ok {
		_spec.SetField(menu.FieldCarryParam, field.TypeBool, value)
		_node.CarryParam = value
	}
	if value, ok := _c.mutation.HideChildrenInMenu(); ok {
		_spec.SetField(menu.FieldHideChildrenInMenu, field.TypeBool, value)
		_node.HideChildrenInMenu = value
	}
	if value, ok := _c.mutation.Affix(); ok {
		_spec.SetField(menu.FieldAffix, field.TypeBool, value)
		_node.Affix = value
	}
	if value, ok := _c.mutation.DynamicLevel(); ok {
		_spec.SetField(menu.FieldDynamicLevel, field.TypeUint32, value)
		_node.DynamicLevel = value
	}
	if value, ok := _c.mutation.RealPath(); ok {
		_spec.SetField(menu.FieldRealPath, field.TypeString, value)
		_node.RealPath = value
	}
	if nodes := _c.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   menu.RolesTable,
			Columns: menu.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menu.ParentTable,
			Columns: []string{menu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menu.ChildrenTable,
			Columns: []string{menu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MenuCreateBulk is the builder for creating many Menu entities in bulk.
type MenuCreateBulk struct {
	config
	err      error
	builders []*MenuCreate
}

// Save creates the Menu entities in the database.
func (_c *MenuCreateBulk) Save(ctx context.Context) ([]*Menu, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Menu, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MenuCreateBulk) SaveX(ctx context.Context) []*Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
