// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/suyuan32/simple-admin-core/pkg/ent/runtime.go

const (
	Version = "v0.11.9"                                         // Version of ent codegen.
	Sum     = "h1:dbbCkAiPVTRBIJwoZctiSYjB7zxQIBOzVSU5H9VYIQI=" // Sum of ent codegen.
)
